apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgres-deployment

spec:
  replicas: 1
  selector: 
    matchLabels:
      app: postgres

  template:
    metadata:
      labels: 
        app: postgres
    spec:
      containers:
        - name: docmost-postgres
          image: postgres:17
          env:
            - name: POSTGRES_USER
              value: postgres_user
            - name: POSTGRES_DB
              value: postgres_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docmost-secrets
                  key: POSTGRES_PASSWORD
