FROM node:20-alpine as base
RUN npm install -g pnpm

FROM base as build
WORKDIR /app
COPY package.json pnpm*.yaml ./
COPY /apps/client/package.json ./apps/client/
COPY /apps/server/package.json ./apps/server/
COPY packages/editor-ext/package.json ./packages/editor-ext/
COPY /patches ./patches
COPY .npmrc ./
RUN pnpm install --frozen-lockfile

COPY . .
ENV PATH="/app/node_modules/.bin:$PATH"
RUN pnpm build

FROM base 
WORKDIR /app
COPY package.json pnpm*.yaml ./
COPY /apps/client/package.json ./apps/client/
COPY /apps/server/package.json ./apps/server/
COPY packages/editor-ext/package.json ./packages/editor-ext/

COPY --from=build /app/apps/client/dist ./apps/client/dist
COPY --from=build /app/apps/server/dist ./apps/server/dist
COPY --from=build /app/packages/editor-ext/dist ./packages/editor-ext/dist
COPY /patches ./patches
COPY .npmrc ./

RUN pnpm install --prod --frozen-lockfile

EXPOSE 3000

CMD ["pnpm", "start"]